<?php

return [
    'pddikti' => [
        'driver' => 'oracle',
        'tns' => env('DB_TNS_PDDIKTI', ''),
        'host' => env('DB_HOST_PDDIKTI', ''),
        'port' => env('DB_PORT_PDDIKTI', '1521'),
        'database' => env('DB_DATABASE_PDDIKTI', ''),
        'service_name' => env('DB_SERVICE_NAME_PDDIKTI', ''),
        'username' => env('DB_USERNAME_PDDIKTI', ''),
        'password' => env('DB_PASSWORD_PDDIKTI', ''),
        'charset' => env('DB_CHARSET_PDDIKTI', 'AL32UTF8'),
        'prefix' => env('DB_PREFIX_PDDIKTI', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX_PDDIKTI', ''),
        'edition' => env('DB_EDITION_PDDIKTI', 'ora$base'),
        'server_version' => env('DB_SERVER_VERSION_PDDIKTI', '11g'),
        'load_balance' => env('DB_LOAD_BALANCE_PDDIKTI', 'yes'),
        'max_name_len' => env('ORA_MAX_NAME_LEN_PDDIKTI', 30),
        'dynamic' => [],
        'sessionVars' => [
            'NLS_TIME_FORMAT' => 'HH24:MI:SS',
            'NLS_DATE_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
            'NLS_NUMERIC_CHARACTERS' => '.,',
        ],
    ],
    'istts_kampus' => [
        'driver' => 'oracle',
        'tns' => env('DB_TNS_ISTTSKAMPUS', ''),
        'host' => env('DB_HOST_ISTTSKAMPUS', ''),
        'port' => env('DB_PORT_ISTTSKAMPUS', '1521'),
        'database' => env('DB_DATABASE_ISTTSKAMPUS', ''),
        'service_name' => env('DB_SERVICE_NAME_ISTTSKAMPUS', ''),
        'username' => env('DB_USERNAME_ISTTSKAMPUS', ''),
        'password' => env('DB_PASSWORD_ISTTSKAMPUS', ''),
        'charset' => env('DB_CHARSET_ISTTSKAMPUS', 'AL32UTF8'),
        'prefix' => env('DB_PREFIX_ISTTSKAMPUS', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX_ISTTSKAMPUS', ''),
        'edition' => env('DB_EDITION_ISTTSKAMPUS', 'ora$base'),
        'server_version' => env('DB_SERVER_VERSION_ISTTSKAMPUS', '11g'),
        'load_balance' => env('DB_LOAD_BALANCE_ISTTSKAMPUS', 'yes'),
        'max_name_len' => env('ORA_MAX_NAME_LEN_ISTTSKAMPUS', 30),
        'dynamic' => [],
        'sessionVars' => [
            'NLS_TIME_FORMAT' => 'HH24:MI:SS',
            'NLS_DATE_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
            'NLS_NUMERIC_CHARACTERS' => '.,',
        ],
    ],
    'istts_dosen' => [
        'driver' => 'oracle',
        'tns' => env('DB_TNS_ISTTSDOSEN', ''),
        'host' => env('DB_HOST_ISTTSDOSEN', ''),
        'port' => env('DB_PORT_ISTTSDOSEN', '1521'),
        'database' => env('DB_DATABASE_ISTTSDOSEN', ''),
        'service_name' => env('DB_SERVICE_NAME_ISTTSDOSEN', ''),
        'username' => env('DB_USERNAME_ISTTSDOSEN', ''),
        'password' => env('DB_PASSWORD_ISTTSDOSEN', ''),
        'charset' => env('DB_CHARSET_ISTTSDOSEN', 'AL32UTF8'),
        'prefix' => env('DB_PREFIX_ISTTSDOSEN', ''),
        'prefix_schema' => env('DB_SCHEMA_PREFIX_ISTTSDOSEN', ''),
        'edition' => env('DB_EDITION_ISTTSDOSEN', 'ora$base'),
        'server_version' => env('DB_SERVER_VERSION_ISTTSDOSEN', '11g'),
        'load_balance' => env('DB_LOAD_BALANCE_ISTTSDOSEN', 'yes'),
        'max_name_len' => env('ORA_MAX_NAME_LEN_ISTTSDOSEN', 30),
        'dynamic' => [],
        'sessionVars' => [
            'NLS_TIME_FORMAT' => 'HH24:MI:SS',
            'NLS_DATE_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_FORMAT' => 'YYYY-MM-DD HH24:MI:SS',
            'NLS_TIMESTAMP_TZ_FORMAT' => 'YYYY-MM-DD HH24:MI:SS TZH:TZM',
            'NLS_NUMERIC_CHARACTERS' => '.,',
        ],
    ],
];
